---
output: 
pagetitle: "Audit Reports"
resource_files:
- rscript/*
- sensitive/*
- www/*
---

```{r include=FALSE, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>", echo = FALSE, fig.width = 6
)
```


```{r load libraries, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
library(downloadthis)
library(tidyverse)
library(gt)
library(here)
library(lubridate)
```


```{r}
#Define Functions

# This function makes the data tables
mkd_table <- function(err_data, title, subtitle) {
  gt(err_data) %>%
  tab_header(
    title = md(title),
    subtitle = paste("Error Message: ", subtitle)
    ) %>%
  tab_options(
    heading.align = "left",
    table.border.top.color = "white",
    column_labels.border.bottom.color = "black",
    table.align = "left",
    table.width = pct(100)
  ) %>%
  tab_style(
    style = list(
      cell_text(color = "#2ECC40")
    ),
    locations = cells_body(
      columns = "term",
      rows = season == "Summer")
  ) %>%
  tab_style(
    style = list(
      cell_text(color = "#FF4136")
    ),
    locations = cells_body(
      columns = "term",
      rows = season == 'Spring')
  ) %>%
  tab_style(
    style = list(
      cell_text(color = "#0074D9")
    ),
    locations = cells_body(
      columns = "term",
      rows = season == 'Fall')
  ) %>%
    cols_align(
      align = "auto",
      columns = everything()
    ) %>%
    opt_css(
      css = "
      .gt_title {
                  font-size: 1.2em !important;
                  font-weight: 600 !important;
                }
                
                .gt_subtitle {
                  color: red !important;
                  font-size: 1em !important;
                }
                
                .gt_table:not(:first-child) {
                  margin-bottom: 2em; 
                }
      "
    )
}

# this function controls the download data button
download_data <- function(list_data, output_name){
  Filter(nrow, {{list_data}}) %>%
    download_this(
    output_name = (output_name),
    output_extension = ".xlsx",
    button_label = "Download",
    button_type = "primary",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
source(here::here('rscript', 'data_pull.R'))
source(here::here('rscript', 'student_checks.R'))
source(here::here('rscript', 'course_checks.R'))

```

## Audit Reports {.tabset}
*Last Updated: `r unique(as_date(student_sql$daterun))`*

### Demographics

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_01) > 0) {
  mkd_table(demo_check_01, "Gender", unique(demo_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
             banner_id = md("**Student ID**"),
             first_name = md("**First Name**"),
             last_name = md("**Last Name**"),
             gender = md("**Gender**"),
             error_message = md("**Error Message**"),
             banner_table = md("**Table Name**"),
             banner_column = md("**Column Name**")
             ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_02) > 0) {
mkd_table(demo_check_02, "County - US", unique(demo_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_country = md("**Country**"),
               admit_state = md("**State**"),
               admit_county = md("**County**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_03) > 0) {
mkd_table(demo_check_03, "State", unique(demo_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_state = md("**State**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_04) > 0) {
  mkd_table(demo_check_04, "County - Utah", unique(demo_check_04$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_country = md("**Country**"),
               admit_state = md("**State**"),
               admit_county = md("**County**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
    }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_05) > 0) {
  mkd_table(demo_check_05, "Missing Country", unique(demo_check_05$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_country = md("**Country**"),
               admit_state = md("**State**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
    }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_06) > 0) {
  mkd_table(demo_check_06, "High School Code", unique(demo_check_06$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               age = md("**Age**"),
               high_school_code = md("**HS Code**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```


```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_07) > 0) {
  mkd_table(demo_check_07, "High School Code", unique(demo_check_07$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               age = md("**Age Code**"),
               high_school_code = md("**HS Code**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_08) > 0) {
  mkd_table(demo_check_08, "Duplicate SSN", unique(demo_check_08$error_message)) %>%
    cols_label(banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               ssn_masked = md("**SSN**"),
               birth_date = md("**DOB**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "term", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_09) > 0) {
  mkd_table(demo_check_09, "SSN Format", unique(demo_check_09$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               ssn_masked   = md("**SSN**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_10) > 0) {
  mkd_table(demo_check_10, "Missing citizenship", unique(demo_check_10$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               citz_code = md("**Citizenship Code**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_11) > 0) {
  mkd_table(demo_check_11, "High School Graduation Date", unique(demo_check_11$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_type = md("**Student Type**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               age = md("**Age**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_12) > 0) {
  mkd_table(demo_check_12, "Duplicate High School", unique(demo_check_12$error_message)) %>%
    cols_label(banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               hs_code = md("**HS Code**"),
               hs_description = md("**HS Description**"),
               hs_graduation_date = md("**HS Graduation Date**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**"),
               dupe_count = md("**Count**")
               ) %>%
    cols_hide(c("error_message", "banner_table", "banner_column", "term", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_13) > 0) {
  mkd_table(demo_check_13, "Citizenship", unique(demo_check_13$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               citz_code = md("**Citizen Code**"),
               admit_state = md("**State**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_14) > 0) {
  mkd_table(demo_check_14, "Undocumented Students", unique(demo_check_14$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               citz_code = md("**Citizen Code**"),
               admit_state = md("**State**"),
               high_school_code = md("**High School Code**"),
               high_school_desc = md("**High School**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_15) > 0) {
  mkd_table(demo_check_15, "Age", unique(demo_check_15$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               age = md("**Age**"),
               high_school_grad_date = md("**HS Grad Date**"),
               entry_action = md("**Entry Action**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```


```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
demo_list <- list(demo_check_01, demo_check_02, demo_check_03, demo_check_04, demo_check_05, demo_check_06, demo_check_07, demo_check_08, demo_check_09, demo_check_10, demo_check_11, demo_check_12, demo_check_13, demo_check_14, demo_check_15) 
download_data(demo_list, 'demographics')
```

&nbsp;

### International Students
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(int_error_01) > 0) {
mkd_table(int_error_01, "Visa Type & Citizenship Code", unique(int_error_01$error_message)) %>%
      cols_label(term = md("**Term**"),
                 banner_id = md("**Student ID**"),
                 first_name = md("**First Name**"),
                 last_name = md("**Last Name**"),
                 citz_code = md("**Citizen Code**"),
                 visa_type = md("**Visa Type**"),
                 nationality_desc = md("**Nationality**"),
                 error_message = md("**Error Message**"),
                 banner_table = md("**Table Name**"),
                 banner_column = md("**Column Name**")
                 ) %>%
      cols_hide(c("error_message", "nationality_desc", "season"))
      }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
int_list <- list(int_error_01) 
download_data(int_list, 'international')
```

&nbsp;

### Degrees & Programs
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(programs_check_01) > 0) {
  mkd_table(programs_check_01, "Degrees & Programs", unique(programs_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               cur_prgm = md("**Program 1**"),
               cur_prgm_2 = md("**Program 2**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
    }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(programs_check_02) > 0) {
  mkd_table(programs_check_02, "High School Code", unique(programs_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               cur_prgm = md("**Program**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(programs_check_03) > 0) {
  mkd_table(programs_check_03, "Missing Program", unique(programs_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               degree = md("**Degree**"),
               major_code = md("**Major Code**"),
               cur_prgm = md("**Program**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
programs_list <- list(programs_check_01, programs_check_02, programs_check_03) 
download_data(programs_list, 'degrees_programs')
```

&nbsp;

### Student Type
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_01) > 0) {
  mkd_table(stype_check_01, "Returning Students", unique(stype_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               first_term_enrolled_start_date = md("**First Term Enrolled Date**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_02) > 0) {
  mkd_table(stype_check_02, "High School Concurrent Student", unique(stype_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               term_start_date = md("**Start Term Date**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               student_type = md("**Student Type**"),
               entry_action= md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_03) > 0) {
  mkd_table(stype_check_03, "High School Concurrent Student & Program", unique(stype_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               cur_prgm = md("**Program**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_04) > 0) {
  mkd_table(stype_check_04, "Personal Interest Student", unique(stype_check_04$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               cur_prgm = md("**Program**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_05) > 0) {
  mkd_table(stype_check_05, "Student Level", unique(stype_check_05$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_06) > 0) {
  mkd_table(stype_check_06, "Student Enrollment", unique(stype_check_06$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               first_term_enrolled = md("**First Term Enrolled**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_07) > 0) {
  mkd_table(stype_check_07, "Transfer Student", unique(stype_check_07$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               last_transfer_term = md("**Last Transfered Term**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_08) > 0) {
  mkd_table(stype_check_08, "Student Level", unique(stype_check_08$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_09) > 0) {
  mkd_table(stype_check_09, "Student Cohort", unique(stype_check_09$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               sgrchrt_chrt_code = md("**Cohort**"),
               last_term_enrolled = md("**Last Term Enrolled**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
# if(nrow(stype_check_10) > 0) {
#   mkd_table(stype_check_10, "First-time Freshman", unique(stype_check_10$error_message)) %>%
#     cols_label(term = md("**Term**"),
#                
#                banner_id = md("**Student ID**"),
#                first_name = md("**First Name**"),
#                last_name = md("**Last Name**"),
#                first_term_enrolled = md("**First Term Enrolled**"),
#                high_school_grad_date = md("**HS Graduation Date**"),
#                days_since_hs_graduation = md("**Days Since HS Graduation**"),
#                student_type = md("**Student Type**"),
#                entry_action = md("**Entry Action**"),
#                error_message = md("**Error Message**")
#                ) %>%
#     cols_hide(c('error_message', 'term_start_date')) %>%
#   br()
# }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_11) > 0) {
  mkd_table(stype_check_11, "Student Enrollment", unique(stype_check_11$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               first_term_enrolled = md("**First Term Enrolled**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_12) > 0) {
  mkd_table(stype_check_12, "Transfer Student", unique(stype_check_12$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               last_transfer_term = md("**Last Transfer Term**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_13) > 0) {
  mkd_table(stype_check_13, "Student Level", unique(stype_check_13$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_14) > 0) {
  mkd_table(stype_check_14, "Student Level", unique(stype_check_14$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
student_list <- list(stype_check_01, stype_check_02, stype_check_03, stype_check_04, stype_check_05,
                      stype_check_06, stype_check_07, stype_check_08, stype_check_09, stype_check_10,
                      stype_check_11, stype_check_12, stype_check_13, stype_check_14) 
download_data(student_list, 'student_type')
```

&nbsp;

### Courses

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_01) > 0) {
  mkd_table(crse_check_01, "Cancelled Course with Enrollments", unique(crse_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_02) > 0) {
  mkd_table(crse_check_02, "Course Section", unique(crse_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               start_time_1 = md("**Start Time**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season")) %>%
    cols_align(align = "right", columns = start_time_1)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_03) > 0) {
  mkd_table(crse_check_03, "Budget Code", unique(crse_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               budget_code = md("**Budge Code**"),
               enrollment = md("**Enrollment**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_04) > 0) {
  mkd_table(crse_check_04, "Budget Code", unique(crse_check_04$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               budget_code = md("**Budget Code**"),
               enrollment = md("**Enrollment**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```


```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
# if(nrow(crse_check_05) > 0) {
#   mkd_table(crse_check_05, "Budget Code", unique(crse_check_05$error_message)) %>%
#     cols_label(term = md("**Term**"),
#                crn = md("**CRN**"),
#                subject_code = md("**Subject**"),
#                section_number = md("**Section**"),
#                budget_code = md("**Budget Code**"),
#                enrollment = md("**Enrollment**"),
#                error_message = md("**Error Message**")
#                ) %>%
#     cols_hide(c("error_message", "season"))
# }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_06) > 0) {
  mkd_table(crse_check_06, "Online Courses", unique(crse_check_06$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               campus_code = md("**Campus**"),
               instruction_method = md("**Instruction Method**"),
               budget_code = md("**Budget Code**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_07) > 0) {
  mkd_table(crse_check_07, "Online Courses", unique(crse_check_07$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               campus_code = md("**Campus**"),
               instruction_method = md("**Instruction Method**"),
               budget_code = md("**Budget Code**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```


```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_08) > 0) {
  mkd_table(crse_check_08, "Courses & Rooms", unique(crse_check_08$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               building_code_1 = md("**Building**"),
               room_code_1 = md("**Room**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
course_list <- list(crse_check_01, crse_check_02, crse_check_03, crse_check_04, #crse_check_05,
                      crse_check_06, crse_check_07, crse_check_08) 
download_data(course_list, 'courses')
```

&nbsp;

### Schedule Type

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_01) > 0) {
  mkd_table(schd_check_01, "Schedule Type", unique(schd_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               schedule_code = md("**Schedule**"),
               credit_hours = md("**Credit Hours**"),
               lecture_hours = md("**Lecture Hours**"),
               lab_hours = md("**Lab Hours**"),
               other_hours = md("**Other Hours**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_02) > 0) {
  mkd_table(schd_check_02, "Schedule Type", unique(schd_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               schedule_code = md("**Schedule**"),
               credit_hours = md("**Credit Hours**"),
               lecture_hours = md("**Lecture Hours**"),
               lab_hours = md("**Lab Hours**"),
               other_hours = md("**Other Hours**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_03) > 0) {
  mkd_table(schd_check_03, "Schedule Type", unique(schd_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               schedule_code = md("**Schedule**"),
               credit_hours = md("**Credit Hours**"),
               lecture_hours = md("**Lecture Hours**"),
               lab_hours = md("**Lab Hours**"),
               other_hours = md("**Other Hours**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_04) > 0) {
  mkd_table(schd_check_04, "Schedule Type", unique(schd_check_04$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               schedule_code = md("**Schedule**"),
               credit_hours = md("**Credit Hours**"),
               lecture_hours = md("**Lecture Hours**"),
               lab_hours = md("**Lab Hours**"),
               other_hours = md("**Other Hours**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```


```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_05) > 0) {
  mkd_table(schd_check_05, "Schedule Type", unique(schd_check_05$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               schedule_code = md("**Schedule**"),
               credit_hours = md("**Credit Hours**"),
               lecture_hours = md("**Lecture Hours**"),
               lab_hours = md("**Lab Hours**"),
               other_hours = md("**Other Hours**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_06) > 0) {
  mkd_table(schd_check_06, "Schedule Type", unique(schd_check_06$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               schedule_code = md("**Schedule**"),
               credit_hours = md("**Credit Hours**"),
               lecture_hours = md("**Lecture Hours**"),
               lab_hours = md("**Lab Hours**"),
               other_hours = md("**Other Hours**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_07) > 0) {
  mkd_table(schd_check_07, "Schedule Type", unique(schd_check_07$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               schedule_code = md("**Schedule**"),
               credit_hours = md("**Credit Hours**"),
               lecture_hours = md("**Lecture Hours**"),
               lab_hours = md("**Lab Hours**"),
               other_hours = md("**Other Hours**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_08) > 0) {
  mkd_table(schd_check_08, "Schedule Type: Programs", unique(schd_check_08$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               program_type = md("**Program Type**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_09) > 0) {
  mkd_table(schd_check_09, "Schedule Type: Programs", unique(schd_check_09$error_message)) %>%
    cols_label(term = md("**Term**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               program_type = md("**Program Type**"),
               program_type = md("**Program Type**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(schd_check_10) > 0) {
  mkd_table(schd_check_10, "Schedule Type: Programs", unique(schd_check_10$error_message)) %>%
    cols_label(term = md("**Term**"),
               subject_code = md("**Subject**"),
               course_number = md("**Course**"),
               program_type = md("**Program Type**"),
               program_type = md("**Program Type**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
schd_list <- list(schd_check_01, schd_check_02, schd_check_03, schd_check_04, schd_check_05,
                      schd_check_06, schd_check_07, schd_check_08, schd_check_09, schd_check_10) 
download_data(schd_list, 'schedule_types')
```

&nbsp;

### HS Concurrent Enrollment

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(ce_check_01) > 0) {
  mkd_table(ce_check_01, "SSID", unique(ce_check_01$error_message)) %>%
    cols_label(banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               ssid = md("**SSID**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season", "term"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(ce_check_02) > 0) {
  mkd_table(ce_check_02, "SSID", unique(ce_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               ssid = md("**SSID**"),
               ssid_length= md("**SSID Length**"),
               banner_table = md("**Table Name**"),
               banner_column = md("**Column Name**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

&nbsp;

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
ce_list <- list(ce_check_01, ce_check_02) 
download_data(ce_list, 'HS Concurrent Enrollment')
```

&nbsp;

### IE Audits
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(ie_check_01) > 0) {
  mkd_table(ie_check_01, "Student Type vs Entry Action", unique(ie_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               first_term_enrolled = md("**First Term Enrolled**"),
               last_term_enrolled = md("**Last Term Enrolled**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(c("error_message", "season"))
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
ie_list <- list(ie_check_01) 
download_data(ie_list, 'ie_audits')
```

&nbsp;